version: "1"
services:
  dev:
    container_name: swatch-dev
    user: vscode
    privileged: true
    shm_size: "256mb"
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/lab/swatch:cached
      - ./config/config.yml:/config/config.yml:ro
      - ./debug:/media/swatch
    ports:
      - "4500:4500"
    entrypoint: ["sudo", "/init"]
    command: /bin/sh -c "while sleep 1000; do :; done"
