name: swatch
description: Swatch frontend.


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.2
  collapsible_sidebar: ^2.0.1+2
  flutter_layout_grid: ^1.0.3

  # IO
  http: ^0.13.4
  window_location_href: ^1.0.0

  # Util
  intl: ^0.17.0

dev_dependencies:

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - icons/swatch.png
    - icons/
    - web/
